name: PR Artifact Upload

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, synchronize, and reopen events

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the code in the PR

      # Step 2: Set up Python (or other environment)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust this based on your project needs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Step 4: Generate artifact (replace with your own logic)
      - name: Generate artifact
        run: |
          New-Item -Path "artifact" -ItemType "Directory" -Force
          "This is a test artifact" | Out-File -FilePath "artifact/test_file.txt"

      # Step 5: Debug: List current directory contents (optional but helpful)
      - name: List current directory contents
        run: |
          dir

      # Debug: List contents of the artifact folder
      - name: List contents of the artifact folder
        run: |
          dir ${{ github.workspace }}\artifact

      # Step 6: Upload Artifact with absolute path
      - name: Upload Artifact
        uses: actions/upload-artifact@v3  # Ensure you're using v3
        with:
          name: pr-artifact  # Artifact name
          path: ${{ github.workspace }}\artifact\*  # Explicit path (absolute path for Windows)
