name: PR Artifact Upload
 
on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, synchronize, and reopen events
 
jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the code in the PR
 
      - name: Set up Python (or other environment)
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust this based on your project needs
 
      - name: Install dependencies
        run: |
          # Example: If you're using Python, install dependencies
          python -m pip install -r requirements.txt
 
      - name: Generate artifact (replace with your own logic)
        run: |
          # Example: Here you might run a script that generates an artifact
          New-Item -Path "artifact" -ItemType "Directory" -Force
          "This is a test artifact" | Out-File -FilePath "artifact/test_file.txt"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3  # Upload the artifact
        with:
          name: pr-artifact  # Artifact name
          path: artifact/*  # Path to the artifact to be uploaded